replicaCount: 1

image:
  repository: grafana/grafana
  tag: latest

container:
  port: 3000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: grafana.localdev.me
      paths:
        - path: /
          pathType: Prefix

fullnameOverride: ""
nameOverride: ""