name: CI/CD - Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.2  # or latest version

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.27.0  # match your cluster version

    - name: Lint Helm chart
      run: |
        helm lint ./helm-chart

